apiVersion: v1
kind: Pod
metadata:
  name: httpbin-pod
  labels:
    app: httpbin
spec:
  initContainers:
  - name: init-networking
    image: t20acr.azurecr.io/init:latest # use your own registry
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: service
    image: kennethreitz/httpbin
    ports:
    - containerPort: 80
  - name: proxy
    image: t20acr.azurecr.io/proxy:latest # use your own registry
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
